### ISSUE TITLE
[Bug] webui1.3.0 extra networks always loading, can't show list

### ISSUE THREAD

**Issue by longgui0318** [canisminor1990/sd-webui-kitchen-theme#102]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

After updating webui 1.3.0, it appears that the content of extra networks keeps loading and cannot be processed successfully, and restarting still cannot solve it. Removing the plugin, the default situation can be processed normally

**Comment by Policturn** [comment]
我也遇到了同样的问题,五月2日的稳定版没有这个问题

**Comment by mrdoug2023** [comment]
> +1

1.3.1中 扩展模型已恢复响应

**Comment by longgui0318** [comment]
The problem was solved in webui 1.3.1
