### ISSUE TITLE
The prompt input box is not resizable.

### ISSUE THREAD

**Issue by Arihany** [canisminor1990/sd-webui-kitchen-theme#26]
It's literally impossible to adjust.
The only downside to an otherwise beautiful theme

**Comment by vanton** [comment]
same here

**Comment by vanton** [comment]
style.css

`[id$="2img_prompt"] textarea {
    color: var(--green-9)!important;
    max-height: 84px;
    overflow-y: auto;
    padding: 12px
}

...

[id$="2img_neg_prompt"] textarea {
    color: var(--magenta-9)!important;
    max-height: 84px;
    overflow-y: auto;
    padding: 12px
}
`
change to 

`[id$="2img_prompt"] textarea {
    color: var(--green-9)!important;
    max-height:  fit-content;
    overflow-y: auto;
    padding: 12px
}

...

[id$="2img_neg_prompt"] textarea {
    color: var(--magenta-9)!important;
    max-height:  fit-content;
    overflow-y: auto;
    padding: 12px
}
`

**Comment by xueqing0622** [comment]
Thanks, It works,

**Comment by Hosiokaa** [comment]
My style CSS on kitchen's theme looks like a mess I searched for max-height: 84px; but it couldnt be found which style.css is this?

**Comment by lp-git-ib** [comment]
Please add this as options checkbox! I beg you!
