### ISSUE TITLE
A proposal for adding default interface state settings | 一个关于添加默认界面状态设置的建议

### ISSUE THREAD

**Issue by anne43983959** [canisminor1990/sd-webui-kitchen-theme#44]
Compared with the original full-width additional network panel, the new additional network sidebar saves page space to a certain extent, but it still takes a while to get used to
Compared with adapting to the difficulty of searching when there are too many additional networks caused by the narrowing of the width, the sidebar of the additional network displayed on the web page by default is actually the biggest trouble, and the explicit content that catches the eye is really troublesome

![QQ截图20230422205041](https://user-images.githubusercontent.com/115604775/233786684-50d207ee-04a6-4a65-9401-4ce86f2e51e2.png)

Figure 1. Explicit content displayed directly on the page

Therefore, I suggest adding a temporary tab to the settings page, or restoring the previous independent settings tab demo, to set whether the left and right sidebars are folded or displayed by default at startup, and you can even add information about the left and right sidebars The default width setting. This can at least improve the current user experience and prevent social death in public

新的附加网络侧边栏相比起原先全屏宽度的附加网络面板一定程度上节约了页面空间，但仍需要一段时间来适应
比起适应因宽度变窄引起附加网络数量过多时检索的困难，默认展示在网页上的附加网络侧边栏本身其实才是最大的麻烦，映入眼帘的露骨内容属实有些困扰

因此，我建议还是在设置页面添加一个临时选项卡，或者恢复之前的独立设置选项卡demo，用来设置左右从侧边栏在启动时是默认折叠还是默认展示，甚至可以添加关于左右侧边栏默认宽度的设置。这样至少可以改善当前的使用体验，不至于在公共场合社会性死亡

**Comment by canisminor1990** [comment]
> 右上角 ⚙ 图标打开设置面板，当前可用设置如下

- Sidebar default width (快捷设置侧边栏默认宽度): 280
- Enable ExtraNetwork Sidebar (是否启用模型侧边栏): true
- ExtraNetwork Sidebar default Width (模型侧边栏默认宽度): 340
- ExtraNetwork default card size (模型侧边栏卡片默认尺寸): 86

侧边栏展开状态改为缓存记录，刷新浏览器时会保持前一次的折叠转台

**Comment by anne43983959** [comment]
> ![image](https://user-images.githubusercontent.com/17870709/233793561-18f86581-1fa9-4521-813f-6205ee6776f2.png)
> 
> > 右上角 ⚙ 图标打开设置面板，当前可用设置如下
> 
>     * Sidebar default width (快捷设置侧边栏默认宽度): 280
> 
>     * Enable ExtraNetwork Sidebar (是否启用模型侧边栏): true
> 
>     * ExtraNetwork Sidebar default Width (模型侧边栏默认宽度): 340
> 
>     * ExtraNetwork default card size (模型侧边栏卡片默认尺寸): 86
> 
> 
> 侧边栏展开状态改为缓存记录，刷新浏览器时会保持前一次的折叠转台
> 
> PS: 观察你的截图，发现在火狐浏览器中部分样式无法得到适配，目前开发和测试环境只能保证在 Chrome,Edge, Safari 中还原

选择火狐其实有两方面原因，第一个肯定是火狐是默认浏览器，所以默认打开肯定是火狐，另外一点是在Chrome浏览器，滑动条会全部变成灰色的，如下图所示：
![QQ截图20230423112552](https://user-images.githubusercontent.com/115604775/233818180-35c1dcbc-4218-40a4-90b5-84ff852c7201.png)
![QQ截图20230423112459](https://user-images.githubusercontent.com/115604775/233818187-22d4835c-0103-4472-bc50-3da0a371991f.png)

**Comment by canisminor1990** [comment]
因为样式就是灰色的, 悬浮才会变蓝, 火狐下是样式没兼容才会默认就是蓝色
