### ISSUE TITLE
Civitai overlay Icons not working

### ISSUE THREAD

**Issue by Piscabo** [canisminor1990/sd-webui-kitchen-theme#45]
Don't shoot the messenger. You closed the issue, but it still persists. Only working for "textual_inversion"
![image](https://user-images.githubusercontent.com/123719842/233788757-75e32157-15f7-4008-8cef-84c0322f556e.png)

No Display on "CKP"
![image](https://user-images.githubusercontent.com/123719842/233788407-d8ed0405-7d61-4b61-9464-7572a7aeb527.png)

**Comment by canisminor1990** [comment]
This problem cannot be fixed temporarily. the temporary solution is as follows:
now you can click top right ⚙ icon in header, and change the Enable ExtraNetwork sidebar to `false`

![image](https://user-images.githubusercontent.com/17870709/233793561-18f86581-1fa9-4521-813f-6205ee6776f2.png)

#44

**Comment by BoyNG** [comment]
No display info also not scroll in list!

**Comment by web-97** [comment]
> 这个问题暂时无法修复。临时解决方法如下： 现在可以点击右上角⚙标题中的图标，并将启用 ExtraNetwork 侧边栏更改为`false`
> 
> ![图像](https://user-images.githubusercontent.com/17870709/233793561-18f86581-1fa9-4521-813f-6205ee6776f2.png)
> 
> #44
Does the temporary solution consider restoring the hidden original button😂

**Comment by canisminor1990** [comment]
https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/pull/122

**Comment by Piscabo** [comment]
> I fix overlay problem in this pr version: [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#122](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/pull/122)

How do I implement it into my Kitchen Theme? PLS.

**Comment by canisminor1990** [comment]
> > I fix overlay problem in this pr version: [butaixianran/Stable-Diffusion-Webui-Civitai-Helper#122](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/pull/122)
> 
> How do I implement it into my Kitchen Theme? PLS.

replace with this fork verison https://github.com/canisminor1990/Stable-Diffusion-Webui-Civitai-Helper
