### ISSUE TITLE
[Bug] Firefox environment support.

### ISSUE THREAD

**Issue by RowanBee** [canisminor1990/sd-webui-kitchen-theme#47]
Some of the UI elements do not behave properly in Firefox, it would be great if support could be added for this browser.

**Comment by uwidev** [comment]
One thing I can say does not work is being able to scroll on the left sidebar when prompts get too long.

**Comment by canisminor1990** [comment]
cause the firefox doesn't support -webkit-fill-available

**Comment by canisminor1990** [comment]
fixed
