### ISSUE TITLE
使用了Civitai-Helper插件,关闭右侧面栏后无法正常打开拓展模型的卡片面板

### ISSUE THREAD

**Issue by Policturn** [canisminor1990/sd-webui-kitchen-theme#48]
生成下面的拓展面板按键无法使用,我这里和那个面板相关的主要插件就是Civitai-Helper,老版本的时候是可以正常使用的

**Comment by canisminor1990** [comment]
这个不一定是插件导致的，刚启动时如果 sd 没有完全加载完点 扩展面板图标就会导致打不开，排除的方法是，当 text2img 的扩展栏打不开时，切换到 img2img 标签看看扩展栏能不能打开，如果能打开就说明的未完全加载导致的错误，你可以尝试重启等一段时间再打开。

**Comment by Policturn** [comment]
测了一下,图生图里面进入就可以打开,但是文生图部分等了很久还是开不开

**Comment by canisminor1990** [comment]
如果要使用侧边栏的话，可以用这个 pr 版本，我修复了  Civitai-Helper 按钮插入的问题: https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper/pull/122

**Comment by Policturn** [comment]
好的,感谢❤

**Comment by Policturn** [comment]
反馈一个兼容性问题,在文件夹内的模型无法加载 Civitai-Helper 按钮,需要用英文路径吗

**Comment by canisminor1990** [comment]
现在可以用原版插件了

**Comment by Policturn** [comment]
是的今天已经发现了,只是还有点小问题,就是在我打开webui并添加了模型再从新载入模型后Civitai-Helper的按钮会消失,并且Civitai-Helper的主动刷新出按钮的选项也失效

**Comment by canisminor1990** [comment]
> 是的今天已经发现了,只是还有点小问题,就是在我打开webui并添加了模型再从新载入模型后Civitai-Helper的按钮会消失,并且Civitai-Helper的主动刷新出按钮的选项也失效

目前没有很好的办法，需要点一下重启webui

**Comment by Policturn** [comment]
好的,我目前也是直接重启webui来解决❤
