### ISSUE TITLE
Copy Ctrl C not working

### ISSUE THREAD

**Issue by Tobe2d** [canisminor1990/sd-webui-kitchen-theme#51]
I just realized only when the theme is activated I cant use ctrl c to copy text from inside the ui. however I can use the right click to copy.
when remove the theme I can use both ctrl c and right click.

Is it a bug?

I am using chrome browser. I have tested it on edge and I can confirm it is the same.

**Comment by canisminor1990** [comment]
🤔
I haven't encountered a similar issue temporarily.
