### ISSUE TITLE
默认不显示侧边栏时无法在启动后展开到预定宽度 | When the sidebar is not displayed by default, it cannot expand to the predetermined width after startup

### ISSUE THREAD

**Issue by anne43983959** [canisminor1990/sd-webui-kitchen-theme#52]
选择默认显示侧边栏的时候，可以在一启动就展开到预定宽度，但关闭后刷新或选择默认不展开时，侧边栏只能展开到一个“默认”的宽度，无法按预定宽度进行展开（我知道相关的修复工作可能已经在进行了，但看到没有人提出这个问题，最终还是选择发出来）

When you choose to display the sidebar by default, it can expand to the predetermined width at startup, but when you refresh after closing or choose not to expand by default, the sidebar can only be expanded to a "default" width, and cannot be expanded according to the predetermined width (I know a related fix may already be in the works, but seeing no one has submited this issue, I finally chose to post it)

**Comment by canisminor1990** [comment]
修复了，还真没发现，不过修复方式暂时是把默认宽度和最小宽度绑定了

**Comment by anne43983959** [comment]
> 修复了，还真没发现，不过修复方式暂时是把默认宽度和最小宽度绑定了

其实这样也行，可以直接把设置里的说明文字就改成侧边栏最小宽度，反正不用的时候也是折叠起来，手动收窄一般用不到
