### ISSUE TITLE
咨询

### ISSUE THREAD

**Issue by s544838371** [canisminor1990/sd-webui-kitchen-theme#54]
**大佬，想咨询下您这边用的SD RPA工具是什么，是用的UiBot Creator还是什么？谢谢**

**Comment by canisminor1990** [comment]
semantic 和 github action

**Comment by s544838371** [comment]
> Semantic 和 GitHub Action

大佬，是我说的有问题，之前看了语雀的直播，有看到在讲案例的时候是用自动化工具来使SD出图，那个工具是啥？MAC专有的吗？ @canisminor1990

**Comment by canisminor1990** [comment]
https://github.com/canisminor1990/kitchen-comfyui

**Comment by s544838371** [comment]
> https://github.com/canisminor1990/kitchen-comfyui

感谢
