### ISSUE TITLE
[Bug] rending same seed (x) and you don't reload the new generated image from prompt but keep the original first generated prompt (x) and Seed image.

### ISSUE THREAD

**Issue by z44sm** [canisminor1990/sd-webui-kitchen-theme#56]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

Rending same seed (x) and you don't reload the new generated image from prompt but keep the original first generated prompt (x) and Seed image., it looks like doesn't work but image is generated.

So if you have seed 44 and put seed 44 in text box rather than -1 the image gets generated in folder but your image in UI is not updating.

But UI looking good.

### 🚦 期望结果 | Expected Behavior

when leaving seed 44 in open field, text box,  the generate image should create a new image in the right window replacing original however it doesn't do it if seed is not -1.

 

### 📷 复现步骤 | Recurrence Steps

Type in Positive prompt
"red cat"
Hit Generate  ... Find Seed of output ... for "red cat"
Put that seed in open text box ...
Change Positive prompt
"blue cat"
Hit Generate ...
....
It will show "red cat" not the "blue cat"

### 📝 补充信息 | Additional Information
Opera browser uses Chrome like extensions if browser style needed.

Please note works perfectly.  if "-1" so whatever your doing differently for same seed is causing issue.

_No response_

**Comment by canisminor1990** [comment]
![2023-04-26 10 33 04](https://user-images.githubusercontent.com/17870709/234451801-153a7f2e-b013-4a67-8c0f-9299e18651cb.gif)

**Comment by Auvere** [comment]
The bug happens for me when using the "Please enter to add new tag" on the left sidebar. Deleting tags there also doesn't work until you adjust the positive prompt manually.

https://user-images.githubusercontent.com/27517093/234854002-2c13c745-601a-422b-853c-7ba4e10137c3.mp4
