### ISSUE TITLE
[Bug] only the header is visible in Safari

### ISSUE THREAD

**Issue by vincentblokker** [canisminor1990/sd-webui-kitchen-theme#58]
### 💻 系统环境 | Operating System

macOS 13.3.1 (22E261) on Apple M1 Max

### 🌐 浏览器 | Browser

Safari 16.4 (18615.1.26.11.23)

### 🐛 问题描述 | Bug Description

With Safari Version 16.4 (18615.1.26.11.23) on MacOS Ventura 13.3.1 (22E261) only the header is visible. When I open the page in Chrome (Version 112.0.5615.137 (Official Build) (arm64)) it works.

I disabled all my adblockers.

![Screenshot 2023-04-26 at 10 50 20](https://user-images.githubusercontent.com/2486217/234523019-49a27905-62a6-4afc-bc1a-b95cf64c543c.png)

### 🚦 期望结果 | Expected Behavior

Should be the same as in Chrome

**Comment by calonye** [comment]
我也是这样；
