### ISSUE TITLE
[Bug] Metadata button is too small

### ISSUE THREAD

**Issue by Dragoy** [canisminor1990/sd-webui-kitchen-theme#59]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

The metadata button is too small in lora styles:
![image](https://user-images.githubusercontent.com/4968313/234929077-cb175743-07bd-4ea3-a256-d013c5000969.png)

### 🚦 期望结果 | Expected Behavior

It should be slightly larger depending on the size of the card, and it should also appear when you hover over the style card itself.

### 📷 复现步骤 | Recurrence Steps

I use the following settings for the panel:
![image](https://user-images.githubusercontent.com/4968313/234930266-9e5332ef-f4c3-4cb0-aef6-c5c8aa043e0a.png)

**Comment by LEv145** [comment]
Quick fix:
```css
.metadata-button {
    top: unset;
    font-size: 22px !important;
}
```
