### ISSUE TITLE
[Bug] Zoom-In slider didn't work

### ISSUE THREAD

**Issue by Dragoy** [canisminor1990/sd-webui-kitchen-theme#60]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

Zoom-In slider didn't work. 
When I move it, nothing happens or changes.

https://user-images.githubusercontent.com/4968313/234932483-e60c618d-d05c-4441-9226-7a2a87943b94.mp4

### 🚦 期望结果 | Expected Behavior

Maybe it should resize the preview styles in real time, but it doesn't do that :(

**Comment by NicoSteyl** [comment]
I had this same issue, and it seems to only happen when the "Default view for extra networks" is set to "cards" in settings -> extra networks. Changing the option to "Thumbs" solved the zoom slider not working for me

**Comment by Dragoy** [comment]
> I had this same issue, and it seems to only happen when the "Default view for extra networks" is set to "cards" in settings -> extra networks. Changing the option to "Thumbs" solved the zoom slider not working for me

I just checked with myself and it really works.
_Default view for Extra Networks - thumbs_
