### ISSUE TITLE
[Bug]调整extraNetwork sidebar中的card不起作用

### ISSUE THREAD

**Issue by l5ee** [canisminor1990/sd-webui-kitchen-theme#61]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

<img width="288" alt="image" src="https://user-images.githubusercontent.com/18050990/235297796-fe0035dc-3888-43b8-bfbd-ad4f65652d1b.png">

调整默认卡片尺寸无变化

### 🚦 期望结果 | Expected Behavior

卡片默认比较大，希望能小一些

### 📷 复现步骤 | Recurrence Steps

必现

**Comment by KenFilmo** [comment]
我是Mac系统，同样的问题。现在解决办法是到WebUI自身设置里面去调整尺寸

**Comment by poppin7c** [comment]
我也是，Mac系统

**Comment by canisminor1990** [comment]
webui 设置中需要更改 Extra-Networks 扩展模型视窗

拇指视图
卡牌宽度: 86
卡牌高度: 128

**Comment by l5ee** [comment]
> 

对，我后面发现了js
