### ISSUE TITLE
[Request] New features in the latest beta webui | 请求下放最新测试版webui的新特性

### ISSUE THREAD

**Issue by anne43983959** [canisminor1990/sd-webui-kitchen-theme#62]
### 🥰 需求描述 | Feature Description

In the latest beta version of the webui(https://github.com/zhouyi311/stable-diffusion-webui-yi/tree/dev-stable), new additional network panel styles have been updated, allowing users to freely add notes to each model and edit them at any time (see the following figure for details)
This may not be very important for embedding and hypernetwork, but for LoRA and LyCORIS, it can prevent users from writing all trigger words into the file name, and sometimes even require additional txt files to store trigger words due to too many trigger words
![QQ截图20230429212730](https://user-images.githubusercontent.com/115604775/235305667-ee3d3683-5423-4a34-b51d-0948098f1614.png)

在最新的测试版webui中，更新了新的额外网络面板样式，使得用户可以自由地为每个模型添加笔记，并随时编辑（详情见下图）
这对于embedding和hypernetwork或许并不是很重要的，但对于LoRA和LyCORIS来说，它可以避免用户将触发词全写进文件名，甚至有时候因为触发词过多需要额外的txt文件来储存触发词

### 🧐 解决方案 | Proposed Solution

代码方面感觉可以直接参考测试版，具体解决方案我个人也没有思路

### 📝 补充信息 | Additional Information

这个测试版webui下，我直接将之前的extensions文件夹做了映射，大部分插件功能都是正常的，唯独kitchen theme失效了，虽然目前还没有实际影响，但A1111的后续更新中很有可能产生类似情况，如果有可能的话，还是希望能在A1111更新前查明失效原因，不然某天A1111突然更新，很有可能措手不及

测试版网址：https://github.com/zhouyi311/stable-diffusion-webui-yi/tree/dev-stable

**Comment by canisminor1990** [comment]
这个不是官方分支吧

**Comment by anne43983959** [comment]
> 这个不是官方分支吧

对，我后来发现确实不是官方分支，但是可以考虑在未来加入这个功能
