### ISSUE TITLE
[Bug] Mobile Bugs.

### ISSUE THREAD

**Issue by pessivesto** [canisminor1990/sd-webui-kitchen-theme#63]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

your theme is awesome However, when using it on an iPad or iPhone, there is a problem with the top sidebar taking up the entire screen. If you press the top arrow button to switch tabs, then the bottom arrow button disappears and stays in the top bar menu forever. Your theme's menu sorting and prompt wizard features are really nice. I want to enjoy this benefit on mobile as well. Please I hope you can solve this problem.

please check this out screenshot link. (it's ipad 12.9) safari and chrome. same. 

http://m-odt.synology.me:5678/mo/sharing/tZq89YKRi

### 🚦 期望结果 | Expected Behavior

please check this out screenshot link. (it's ipad 12.9) safari and chrome. same. 

http://m-odt.synology.me:5678/mo/sharing/tZq89YKRi

**Comment by canisminor1990** [comment]
https://github.com/canisminor1990/sd-webui-kitchen-theme/issues/58
