### ISSUE TITLE
[Request] 

### ISSUE THREAD

**Issue by Piscabo** [canisminor1990/sd-webui-kitchen-theme#67]
### 🥰 需求描述 | Feature Description

A visual interface to be able to select Lora’s in Additional Network

Or the ability to drag-drop die Lora, into the dropdown box like this.
![image](https://user-images.githubusercontent.com/123719842/235535079-5d221a7d-0f0e-4f31-bc0a-3a43ac5f4eb7.png)

### 🧐 解决方案 | Proposed Solution

The possibility to have Visual icons for Additional Network model pick - Lora drop-down pick box or drag from the library.
![image](https://user-images.githubusercontent.com/123719842/235535701-b49c9c9f-cce4-4af4-be8b-395864bc9548.png)

**Comment by canisminor1990** [comment]
😅 too hack and low stability
