### ISSUE TITLE
[Bug] My eye hurts with Light theme....

### ISSUE THREAD

**Issue by jcyuan** [canisminor1990/sd-webui-kitchen-theme#70]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

![image](https://user-images.githubusercontent.com/850854/236411250-6c77cefb-461b-42e8-9379-e293abf65d6a.png)
i believe there are some bugs out there with this mode, no? because i found that the Dark theme works pretty well.

**Comment by web-97** [comment]
It may be caused by incompatibility with your browser plug-ins (plug-ins such as dark mode), because the theme supports two modes, you can try to turn off these plug-ins, it works fine on my Chrome

**Comment by canisminor1990** [comment]
翻译成英文：看起来像是和其他 theme 插件一起使用造成的兼容问题，比如 Catppuccin Theme
