### ISSUE TITLE
[Bug] lora库显示不全

### ISSUE THREAD

**Issue by Policturn** [canisminor1990/sd-webui-kitchen-theme#72]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Edge

### 🐛 问题描述 | Bug Description

开启后右侧边的拓展模型栏最下面无法显示出来
截图→[https://img1.imgtp.com/2023/05/06/jOv2lHku.png](url)

### 📷 复现步骤 | Recurrence Steps

目前是启动就会出现

**Comment by Array-Cats** [comment]
目前我使用chrome没有遇到这个问题（包括拖动底下缩放条后）

**Comment by lonelyman0907** [comment]
If the lora is based on SD XL, it will not showing when you choose other models
