### ISSUE TITLE
[Question] 主界面的错误？

### ISSUE THREAD

**Issue by zoxokm** [canisminor1990/sd-webui-kitchen-theme#73]
### 🧐 问题描述 | Proposed Solution

安装了一些插件卸载后 主界面出现无效横栏无法去除，使用主题有，用原生界面正常，请问这是不是BUG！或者如何解决，如图！
[出错界面](https://photos.app.goo.gl/7Q7pU4A9GkRtwsPH9)
[正常界面](https://photos.app.goo.gl/Sm8JYo75o3FyzVof7)

**Comment by gzizumi** [comment]
@canisminor1990  你好作者，我也遇到了这种情况！而且这个bug可以跨越各个我使用的整合AI，我理解应该是有一份遗留在用户PC的设置文件影响了这个地方的错误显示，因为我删除SD也没有解决问题，完全初始化kitchen应该是奏效的，但是我找不到这个文件和方法。谢谢你能看到，也谢谢你制作的插件！
![image](https://github.com/canisminor1990/sd-webui-kitchen-theme/assets/132351461/14dbf269-bf2a-4736-a2df-8f7268d4741f)
"😇 Help Wanted"
