### ISSUE TITLE
[Bug] Extra Networks Sidebar Broken on Vladmandic WebUI Fork

### ISSUE THREAD

**Issue by MiniCoperations** [canisminor1990/sd-webui-kitchen-theme#75]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

The Sidebar for Extra Networks is broken on the Vladmandic Fork due to the Descriptions function breaking the UI. 
As of right now this function cannot be easily toggled in settings so the conflict cannot be avoided.

With issues such as:

- Overlap of the thumbnails on top of the description textbox.
- Icons are not displayed over thumbnails.
- Close button by search bar is redundant and doesn't function anyway.

![image](https://user-images.githubusercontent.com/74561161/236712900-d90ba51d-ebb7-4eb5-9143-1c58760716a0.png)

### 🚦 期望结果 | Expected Behavior

- UI should adjust to the presence of the extra Textbox and move the thumbnails down to avoid overlap.
- Extra close button should be removed.
- Icons should be properly displayed on hover over thumbnails.

### 📷 复现步骤 | Recurrence Steps

Install extension on the [WebUI fork by Vladmandic](https://github.com/vladmandic/automatic).

**Comment by canisminor1990** [comment]
won't support other fork webui version temporarily

**Comment by Goatle** [comment]
@MiniCoperations 

I made some css adjustments of my own to fix this along with some other annoyances. Put them in the style.css at the very bottom.
YMMV.
`
div#txt2img_description_input.block.gradio-textbox.svelte-mppz8v.padded label.svelte-1pie7s6 textarea.scroll-hide.svelte-1pie7s6 {
    display: block;
    height: 70px;
    margin-bottom: 10px !important;
    resize: none;
    overflow-y: scroll;
    overflow-x: hidden;
}

.extra-networks .extra-network-subdirs {
    flex-wrap: wrap;
    align-items: center;
    gap: 4px;
    margin-top: 55px;
    margin-bottom: 12px;
    display: flex;
    padding: 0 !important;
    max-height: 200px !important;
    overflow-y: scroll;
    overflow-x: hidden;
    resize: vertical;
    height: 110px;
}

.extra-networks .actions .additional>ul {
    justify-content: left !important;
    align-items: normal !important;
    margin: 0.25em 0 0.75em 0.25em !important;
    padding: 0 !important;
    display: grid !important;
    font-size: 10px !important;
    white-space: normal !important;
    list-style-position: inside !important;

}
`

**Comment by MiniCoperations** [comment]
This is much better.
@Goatle Thanks so much!
