### ISSUE TITLE
[Request] 能否自适应提示词输入框或者可以手动更改输入框大小

### ISSUE THREAD

**Issue by yuno779** [canisminor1990/sd-webui-kitchen-theme#78]
### 🥰 需求描述 | Feature Description

当我输入很多提示词的时候，因为提示词输入框过于小会导致查看极其困难，并且非常影响使用者进行进行语法纠错
![6df2876ce786f172ee4acd669c96d696](https://github.com/canisminor1990/sd-webui-kitchen-theme/assets/131428984/8062e2af-ec05-441c-b3bd-0269f38d2af3)

### 🧐 解决方案 | Proposed Solution

希望能够和以前Webui原本样式那样自适应提示词框的大小，或者能够手动拖动更改提示词框大小。如果有可能的话，能不能加一个语法自动纠错的按钮

**Comment by hzjdzzh955** [comment]
[https://github.com/canisminor1990/sd-webui-kitchen-theme/issues/26#issuecomment-1518468224](url)

**Comment by hzjdzzh955** [comment]
https://github.com/canisminor1990/sd-webui-kitchen-theme/issues/26#issuecomment-1518468224
