### ISSUE TITLE
[Request] 能否允许用户能将模型选择和VAE选择切换成和原版一样，也就是回到顶部。放在侧边一直打开有点占地方，关了的话又用起来不方便。

### ISSUE THREAD

**Issue by hzjdzzh955** [canisminor1990/sd-webui-kitchen-theme#79]
### 🥰 需求描述 | Feature Description

[Request] 能否允许用户能将模型选择和VAE选择切换成和原版一样，也就是回到顶部。放在侧边一直打开有点占地方，关了的话又用起来不方便，谢谢。

### 🧐 解决方案 | Proposed Solution

将模型选择和VAE选择切换成和原版一样，也就是回到顶部。

**Comment by baifagg** [comment]
> 在设置中增加了悬浮模式

请问怎么启用悬浮模式呢

**Comment by canisminor1990** [comment]
> > 在设置中增加了悬浮模式
> 
> 请问怎么启用悬浮模式呢

右上角齿轮设置按钮

**Comment by amimi818** [comment]
> > > 在设置中增加了悬浮模式
> > 
> > 
> > 请问怎么启用悬浮模式呢
> 
> 右上角齿轮设置按钮

哪个版本有这个功能呢？我是（58a2dea9 (Wed May 17 12:48:21 2023)版，设置里找不到悬浮模式。
--


<br class="Apple-interchange-newline">
</body>
</html>

**Comment by amimi818** [comment]
> > > 在设置中增加了悬浮模式
> > 
> > 
> > 请问怎么启用悬浮模式呢
> 
> 右上角齿轮设置按钮

哪个版本有这个功能呢？我的版本（58a2dea9 (Wed May 17 12:48:21 2023)，设置里找不到悬浮模式。

**Comment by canisminor1990** [comment]
更新下插件版本

**Comment by amimi818** [comment]
这个悬浮功能太棒了，即节省了空间，又保持了使用的便利性！
