### ISSUE TITLE
[Bug] 黑色主题下 tag-autocomplete 插件提示框 < 开头提示 Lora 颜色为白色

### ISSUE THREAD

**Issue by rdmclin2** [canisminor1990/sd-webui-kitchen-theme#82]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

黑色主题下 tag-autocomplete 插件提示框 < 开头提示 Lora 颜色为白色

![image](https://github.com/canisminor1990/sd-webui-kitchen-theme/assets/4705237/a52b35a2-22a9-4971-a60e-8de38762d61f)

### 🚦 期望结果 | Expected Behavior

期望为黑色或者其他区别于白色的颜色

### 📷 复现步骤 | Recurrence Steps

1. 安装 auto-compelte 插件
2. 提示词中输入 <lora:

**Comment by canisminor1990** [comment]
![Uploading image.png…]()
