### ISSUE TITLE
[Bug] thumb视图下附加网络面板无法滚动，尺寸调节滑动条缺失

### ISSUE THREAD

**Issue by anne43983959** [canisminor1990/sd-webui-kitchen-theme#84]
### 💻 系统环境 | Operating System

Windows

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

thumb视图下尺寸调节滑动条缺失，导致在小预览图时过长的文件名遮挡替换预览图按钮的问题无法解决（之前可以通过临时调大预览图解决）

除此，thumb视图下附加网络面板不受鼠标滚轮控制，无法滚动

另外，设置页面无法保持当前的设置，重启后会显示默认内容且与当前的设置并不一致，调整提示词框大小功能也没有正常生效

### 🚦 期望结果 | Expected Behavior

优先恢复附加网络面板的滚动和尺寸调节，其余功能相比起这两个bug是次要矛盾

### 📷 复现步骤 | Recurrence Steps

更新到5月17日之后的版本就会出现

### 📝 补充信息 | Additional Information

bug的表现形式与cozy nest主题在thumb视图下的bug如出一辙，虽然悬浮窗确实很好，但是这个bug逼迫我回滚到了ec31ef6版本

**Comment by canisminor1990** [comment]
能把具体的分支发一下么，在这个 master 最新的 commit 中并没有发现你说的问题，https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/89f9faa63388756314e8a1d96cf86bf5e0663045

**Comment by anne43983959** [comment]
> 能把具体的分支发一下么，在这个 master 最新的 commit 中并没有发现你说的问题，[AUTOMATIC1111/stable-diffusion-webui@89f9faa](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/89f9faa63388756314e8a1d96cf86bf5e0663045)

我当前使用的是master分支的5ab7f21版本，由于b08500c之后的版本无法在页面正确加载生成的图片，所以我暂时停留在了这个版本，不清楚这是否和gradio版本有关

**Comment by anne43983959** [comment]
> 能把具体的分支发一下么，在这个 master 最新的 commit 中并没有发现你说的问题，[AUTOMATIC1111/stable-diffusion-webui@89f9faa](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/89f9faa63388756314e8a1d96cf86bf5e0663045)

刚刚试着在89f9faa版本上更新的了kitchen，故障依旧，但是观察到切换附加网络种类的时候有加载卡顿，此时确实显示了尺寸调节的滑动条，但是等到加载完毕，由于模型数量过多，滑动条已经超出屏幕显示范围了（我当前的显示器配置是双屏上下放置，不清楚是否与此有关，但表现上有点像误估了总高度，导致所有内容全部显示出来禁用了滚动，最终导致滚动失效）

**Comment by canisminor1990** [comment]
https://github.com/canisminor1990/sd-webui-kitchen-theme/assets/17870709/aea0d71d-5b04-49df-9114-ce300e7779e7

暂时没有找到复现的方法

**Comment by anne43983959** [comment]
这是我这边录制的情况，确实是整个侧边栏高度有问题，这个环境是我昨天重新部署的，版本是89f9faa，我现在也不知道复现这个bug需要什么额外条件，因为在我这边只要更新就会出现，如果需要的话我可以提供更多我目前的环境信息

https://github.com/canisminor1990/sd-webui-kitchen-theme/assets/115604775/0706ed53-a98f-4d7e-9126-0a9b9f9486b1

**Comment by anne43983959** [comment]
进一步测试发现，无法滚动的情况只在Chrome上出现，更新了ea13808版本后即便card视图下会误估侧边栏高度，Firefox依然可以完整地滚动整个侧边栏，而thumb视图在Firefox上不会出现任何滚动问题

继续进行进一步测试，发现Firefox上的所有设置都保持了默认参数，遂在Chrome重置了kitchen的设置选项，发现Chrome的问题亦得到解决

故得出结论，是旧版本的残留设置导致界面问题，希望在readme中加入相关引导避免此类情况再次发生

**Comment by anne43983959** [comment]
进一步测试，发现该bug与默认展开状态有关，当关闭默认展开后，滚动随即失效
