### ISSUE TITLE
[Question] 界面显示问题

### ISSUE THREAD

**Issue by yunyan0228** [canisminor1990/sd-webui-kitchen-theme#85]
### 🧐 问题描述 | Proposed Solution

![)KM(9AD9D$3}Y_( 7H}RED5](https://github.com/canisminor1990/sd-webui-kitchen-theme/assets/119416578/fa345582-d457-4a17-8864-572d66445aba)
![AXQ FRLM5PYR}JH3YC{~D_E](https://github.com/canisminor1990/sd-webui-kitchen-theme/assets/119416578/62206fbe-6ada-4b4d-9172-19564653b5d2)
使用插件皮肤后，出现两个不知名空白框

**Comment by canisminor1990** [comment]
Duplicate https://github.com/canisminor1990/sd-webui-kitchen-theme/issues/73
